// This file is autogenerated. Take a look at `Preprocessor` target in RxSwift project 
//
//  CombineLatest+arity.swift
//  RxSwift
//
//  Created by Krunoslav Zaher on 4/22/15.
//  Copyright © 2015 Krunoslav Zaher. All rights reserved.
//

import Foundation



// 2

extension ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType>
        (_ source1: O1, _ source2: O2, debounceDependencies: Bool = false, resultSelector: @escaping (O1.E, O2.E) throws -> Element)
            -> Observable<Element> {
        return CombineLatest2(
            source1: source1.asObservable(), source2: source2.asObservable(),
            debounceDependencies: debounceDependencies, resultSelector: resultSelector
        )
    }
}

extension ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType>
        (_ source1: O1, _ source2: O2, debounceDependencies: Bool = false)
            -> Observable<(O1.E, O2.E)> {
        return CombineLatest2(
            source1: source1.asObservable(), source2: source2.asObservable(),
            debounceDependencies: debounceDependencies,
            resultSelector: { ($0, $1) }
        )
    }
}

final class CombineLatestSink2_<E1, E2, Observer: ObserverType> : CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = CombineLatest2<E1, E2, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil

    init(parent: Parent, observer: Observer, cancel: Cancelable) {
        self._parent = parent
        super.init(arity: 2, observer: observer, cancel: cancel)
    }

    func run(debounceDependencies: Bool) -> Disposable {
        var disposables: [Disposable] = []
        
        if debounceDependencies {
            for (index, source) in _parent.observableSources.enumerated() {
                for leafSource in source.leafSources.deduplicatedByPointer() {
                    let subscription = SingleAssignmentDisposable()
                    
                    let observer = CombineLatestEraseObserver(lock: _lock, parent: self, index: index, this: subscription)
                    subscription.setDisposable(leafSource.subscribeAny { observer.on($0) })
                    disposables.append(subscription)
                }
            }
        }

        let subscription1 = SingleAssignmentDisposable()
        let subscription2 = SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)

        if debounceDependencies {
            // We avoid using MainScheduler here, as we _always_ want these subscriptions to be dispatched
            // asynchronously rather than run directly.
            let mainScheduler = ConcurrentDispatchQueueScheduler(queue: DispatchQueue.main)
            subscription1.setDisposable(_parent._source1.observeOn(mainScheduler).subscribe(observer1))
            subscription2.setDisposable(_parent._source2.observeOn(mainScheduler).subscribe(observer2))
        } else {
         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
        }

        return Disposables.create(disposables + [
                subscription1,
                subscription2
        ])
    }

    override func getResult() throws -> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2)
    }
}

final class CombineLatest2<E1, E2, Result> : Producer<Result> {
    typealias ResultSelector = (E1, E2) throws -> Result

    let _source1: Observable<E1>
    let _source2: Observable<E2>

    let _debounceDependencies: Bool
    let _resultSelector: ResultSelector

    init(source1: Observable<E1>, source2: Observable<E2>, debounceDependencies: Bool, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2

        self._debounceDependencies = debounceDependencies
        self._resultSelector = resultSelector
    }

    override func run<Observer: ObserverType>(_ observer: Observer, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where Observer.Element == Result {
        let sink = CombineLatestSink2_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run(debounceDependencies: _debounceDependencies)
        return (sink: sink, subscription: subscription)
    }
}



// 3

extension ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, debounceDependencies: Bool = false, resultSelector: @escaping (O1.E, O2.E, O3.E) throws -> Element)
            -> Observable<Element> {
        return CombineLatest3(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(),
            debounceDependencies: debounceDependencies, resultSelector: resultSelector
        )
    }
}

extension ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, debounceDependencies: Bool = false)
            -> Observable<(O1.E, O2.E, O3.E)> {
        return CombineLatest3(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(),
            debounceDependencies: debounceDependencies,
            resultSelector: { ($0, $1, $2) }
        )
    }
}

final class CombineLatestSink3_<E1, E2, E3, Observer: ObserverType> : CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = CombineLatest3<E1, E2, E3, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil

    init(parent: Parent, observer: Observer, cancel: Cancelable) {
        self._parent = parent
        super.init(arity: 3, observer: observer, cancel: cancel)
    }

    func run(debounceDependencies: Bool) -> Disposable {
        var disposables: [Disposable] = []
        
        if debounceDependencies {
            for (index, source) in _parent.observableSources.enumerated() {
                for leafSource in source.leafSources.deduplicatedByPointer() {
                    let subscription = SingleAssignmentDisposable()
                    
                    let observer = CombineLatestEraseObserver(lock: _lock, parent: self, index: index, this: subscription)
                    subscription.setDisposable(leafSource.subscribeAny { observer.on($0) })
                    disposables.append(subscription)
                }
            }
        }

        let subscription1 = SingleAssignmentDisposable()
        let subscription2 = SingleAssignmentDisposable()
        let subscription3 = SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)

        if debounceDependencies {
            // We avoid using MainScheduler here, as we _always_ want these subscriptions to be dispatched
            // asynchronously rather than run directly.
            let mainScheduler = ConcurrentDispatchQueueScheduler(queue: DispatchQueue.main)
            subscription1.setDisposable(_parent._source1.observeOn(mainScheduler).subscribe(observer1))
            subscription2.setDisposable(_parent._source2.observeOn(mainScheduler).subscribe(observer2))
            subscription3.setDisposable(_parent._source3.observeOn(mainScheduler).subscribe(observer3))
        } else {
         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
        }

        return Disposables.create(disposables + [
                subscription1,
                subscription2,
                subscription3
        ])
    }

    override func getResult() throws -> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3)
    }
}

final class CombineLatest3<E1, E2, E3, Result> : Producer<Result> {
    typealias ResultSelector = (E1, E2, E3) throws -> Result

    let _source1: Observable<E1>
    let _source2: Observable<E2>
    let _source3: Observable<E3>

    let _debounceDependencies: Bool
    let _resultSelector: ResultSelector

    init(source1: Observable<E1>, source2: Observable<E2>, source3: Observable<E3>, debounceDependencies: Bool, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3

        self._debounceDependencies = debounceDependencies
        self._resultSelector = resultSelector
    }

    override func run<Observer: ObserverType>(_ observer: Observer, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where Observer.Element == Result {
        let sink = CombineLatestSink3_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run(debounceDependencies: _debounceDependencies)
        return (sink: sink, subscription: subscription)
    }
}



// 4

extension ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, debounceDependencies: Bool = false, resultSelector: @escaping (O1.E, O2.E, O3.E, O4.E) throws -> Element)
            -> Observable<Element> {
        return CombineLatest4(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(),
            debounceDependencies: debounceDependencies, resultSelector: resultSelector
        )
    }
}

extension ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, debounceDependencies: Bool = false)
            -> Observable<(O1.E, O2.E, O3.E, O4.E)> {
        return CombineLatest4(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(),
            debounceDependencies: debounceDependencies,
            resultSelector: { ($0, $1, $2, $3) }
        )
    }
}

final class CombineLatestSink4_<E1, E2, E3, E4, Observer: ObserverType> : CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = CombineLatest4<E1, E2, E3, E4, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil

    init(parent: Parent, observer: Observer, cancel: Cancelable) {
        self._parent = parent
        super.init(arity: 4, observer: observer, cancel: cancel)
    }

    func run(debounceDependencies: Bool) -> Disposable {
        var disposables: [Disposable] = []
        
        if debounceDependencies {
            for (index, source) in _parent.observableSources.enumerated() {
                for leafSource in source.leafSources.deduplicatedByPointer() {
                    let subscription = SingleAssignmentDisposable()
                    
                    let observer = CombineLatestEraseObserver(lock: _lock, parent: self, index: index, this: subscription)
                    subscription.setDisposable(leafSource.subscribeAny { observer.on($0) })
                    disposables.append(subscription)
                }
            }
        }

        let subscription1 = SingleAssignmentDisposable()
        let subscription2 = SingleAssignmentDisposable()
        let subscription3 = SingleAssignmentDisposable()
        let subscription4 = SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)

        if debounceDependencies {
            // We avoid using MainScheduler here, as we _always_ want these subscriptions to be dispatched
            // asynchronously rather than run directly.
            let mainScheduler = ConcurrentDispatchQueueScheduler(queue: DispatchQueue.main)
            subscription1.setDisposable(_parent._source1.observeOn(mainScheduler).subscribe(observer1))
            subscription2.setDisposable(_parent._source2.observeOn(mainScheduler).subscribe(observer2))
            subscription3.setDisposable(_parent._source3.observeOn(mainScheduler).subscribe(observer3))
            subscription4.setDisposable(_parent._source4.observeOn(mainScheduler).subscribe(observer4))
        } else {
         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
        }

        return Disposables.create(disposables + [
                subscription1,
                subscription2,
                subscription3,
                subscription4
        ])
    }

    override func getResult() throws -> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4)
    }
}

final class CombineLatest4<E1, E2, E3, E4, Result> : Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4) throws -> Result

    let _source1: Observable<E1>
    let _source2: Observable<E2>
    let _source3: Observable<E3>
    let _source4: Observable<E4>

    let _debounceDependencies: Bool
    let _resultSelector: ResultSelector

    init(source1: Observable<E1>, source2: Observable<E2>, source3: Observable<E3>, source4: Observable<E4>, debounceDependencies: Bool, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4

        self._debounceDependencies = debounceDependencies
        self._resultSelector = resultSelector
    }

    override func run<Observer: ObserverType>(_ observer: Observer, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where Observer.Element == Result {
        let sink = CombineLatestSink4_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run(debounceDependencies: _debounceDependencies)
        return (sink: sink, subscription: subscription)
    }
}



// 5

extension ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, debounceDependencies: Bool = false, resultSelector: @escaping (O1.E, O2.E, O3.E, O4.E, O5.E) throws -> Element)
            -> Observable<Element> {
        return CombineLatest5(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(),
            debounceDependencies: debounceDependencies, resultSelector: resultSelector
        )
    }
}

extension ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, debounceDependencies: Bool = false)
            -> Observable<(O1.E, O2.E, O3.E, O4.E, O5.E)> {
        return CombineLatest5(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(),
            debounceDependencies: debounceDependencies,
            resultSelector: { ($0, $1, $2, $3, $4) }
        )
    }
}

final class CombineLatestSink5_<E1, E2, E3, E4, E5, Observer: ObserverType> : CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = CombineLatest5<E1, E2, E3, E4, E5, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil

    init(parent: Parent, observer: Observer, cancel: Cancelable) {
        self._parent = parent
        super.init(arity: 5, observer: observer, cancel: cancel)
    }

    func run(debounceDependencies: Bool) -> Disposable {
        var disposables: [Disposable] = []
        
        if debounceDependencies {
            for (index, source) in _parent.observableSources.enumerated() {
                for leafSource in source.leafSources.deduplicatedByPointer() {
                    let subscription = SingleAssignmentDisposable()
                    
                    let observer = CombineLatestEraseObserver(lock: _lock, parent: self, index: index, this: subscription)
                    subscription.setDisposable(leafSource.subscribeAny { observer.on($0) })
                    disposables.append(subscription)
                }
            }
        }

        let subscription1 = SingleAssignmentDisposable()
        let subscription2 = SingleAssignmentDisposable()
        let subscription3 = SingleAssignmentDisposable()
        let subscription4 = SingleAssignmentDisposable()
        let subscription5 = SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)

        if debounceDependencies {
            // We avoid using MainScheduler here, as we _always_ want these subscriptions to be dispatched
            // asynchronously rather than run directly.
            let mainScheduler = ConcurrentDispatchQueueScheduler(queue: DispatchQueue.main)
            subscription1.setDisposable(_parent._source1.observeOn(mainScheduler).subscribe(observer1))
            subscription2.setDisposable(_parent._source2.observeOn(mainScheduler).subscribe(observer2))
            subscription3.setDisposable(_parent._source3.observeOn(mainScheduler).subscribe(observer3))
            subscription4.setDisposable(_parent._source4.observeOn(mainScheduler).subscribe(observer4))
            subscription5.setDisposable(_parent._source5.observeOn(mainScheduler).subscribe(observer5))
        } else {
         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))
        }

        return Disposables.create(disposables + [
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5
        ])
    }

    override func getResult() throws -> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5)
    }
}

final class CombineLatest5<E1, E2, E3, E4, E5, Result> : Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5) throws -> Result

    let _source1: Observable<E1>
    let _source2: Observable<E2>
    let _source3: Observable<E3>
    let _source4: Observable<E4>
    let _source5: Observable<E5>

    let _debounceDependencies: Bool
    let _resultSelector: ResultSelector

    init(source1: Observable<E1>, source2: Observable<E2>, source3: Observable<E3>, source4: Observable<E4>, source5: Observable<E5>, debounceDependencies: Bool, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5

        self._debounceDependencies = debounceDependencies
        self._resultSelector = resultSelector
    }

    override func run<Observer: ObserverType>(_ observer: Observer, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where Observer.Element == Result {
        let sink = CombineLatestSink5_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run(debounceDependencies: _debounceDependencies)
        return (sink: sink, subscription: subscription)
    }
}



// 6

extension ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType, O6: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, debounceDependencies: Bool = false, resultSelector: @escaping (O1.E, O2.E, O3.E, O4.E, O5.E, O6.E) throws -> Element)
            -> Observable<Element> {
        return CombineLatest6(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(),
            debounceDependencies: debounceDependencies, resultSelector: resultSelector
        )
    }
}

extension ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType, O6: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, debounceDependencies: Bool = false)
            -> Observable<(O1.E, O2.E, O3.E, O4.E, O5.E, O6.E)> {
        return CombineLatest6(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(),
            debounceDependencies: debounceDependencies,
            resultSelector: { ($0, $1, $2, $3, $4, $5) }
        )
    }
}

final class CombineLatestSink6_<E1, E2, E3, E4, E5, E6, Observer: ObserverType> : CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = CombineLatest6<E1, E2, E3, E4, E5, E6, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil
    var _latestElement6: E6! = nil

    init(parent: Parent, observer: Observer, cancel: Cancelable) {
        self._parent = parent
        super.init(arity: 6, observer: observer, cancel: cancel)
    }

    func run(debounceDependencies: Bool) -> Disposable {
        var disposables: [Disposable] = []
        
        if debounceDependencies {
            for (index, source) in _parent.observableSources.enumerated() {
                for leafSource in source.leafSources.deduplicatedByPointer() {
                    let subscription = SingleAssignmentDisposable()
                    
                    let observer = CombineLatestEraseObserver(lock: _lock, parent: self, index: index, this: subscription)
                    subscription.setDisposable(leafSource.subscribeAny { observer.on($0) })
                    disposables.append(subscription)
                }
            }
        }

        let subscription1 = SingleAssignmentDisposable()
        let subscription2 = SingleAssignmentDisposable()
        let subscription3 = SingleAssignmentDisposable()
        let subscription4 = SingleAssignmentDisposable()
        let subscription5 = SingleAssignmentDisposable()
        let subscription6 = SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)
        let observer6 = CombineLatestObserver(lock: self._lock, parent: self, index: 5, setLatestValue: { (e: E6) -> Void in self._latestElement6 = e }, this: subscription6)

        if debounceDependencies {
            // We avoid using MainScheduler here, as we _always_ want these subscriptions to be dispatched
            // asynchronously rather than run directly.
            let mainScheduler = ConcurrentDispatchQueueScheduler(queue: DispatchQueue.main)
            subscription1.setDisposable(_parent._source1.observeOn(mainScheduler).subscribe(observer1))
            subscription2.setDisposable(_parent._source2.observeOn(mainScheduler).subscribe(observer2))
            subscription3.setDisposable(_parent._source3.observeOn(mainScheduler).subscribe(observer3))
            subscription4.setDisposable(_parent._source4.observeOn(mainScheduler).subscribe(observer4))
            subscription5.setDisposable(_parent._source5.observeOn(mainScheduler).subscribe(observer5))
            subscription6.setDisposable(_parent._source6.observeOn(mainScheduler).subscribe(observer6))
        } else {
         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))
         subscription6.setDisposable(self._parent._source6.subscribe(observer6))
        }

        return Disposables.create(disposables + [
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5,
                subscription6
        ])
    }

    override func getResult() throws -> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5, self._latestElement6)
    }
}

final class CombineLatest6<E1, E2, E3, E4, E5, E6, Result> : Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5, E6) throws -> Result

    let _source1: Observable<E1>
    let _source2: Observable<E2>
    let _source3: Observable<E3>
    let _source4: Observable<E4>
    let _source5: Observable<E5>
    let _source6: Observable<E6>

    let _debounceDependencies: Bool
    let _resultSelector: ResultSelector

    init(source1: Observable<E1>, source2: Observable<E2>, source3: Observable<E3>, source4: Observable<E4>, source5: Observable<E5>, source6: Observable<E6>, debounceDependencies: Bool, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5
        self._source6 = source6

        self._debounceDependencies = debounceDependencies
        self._resultSelector = resultSelector
    }

    override func run<Observer: ObserverType>(_ observer: Observer, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where Observer.Element == Result {
        let sink = CombineLatestSink6_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run(debounceDependencies: _debounceDependencies)
        return (sink: sink, subscription: subscription)
    }
}



// 7

extension ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType, O6: ObservableType, O7: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7, debounceDependencies: Bool = false, resultSelector: @escaping (O1.E, O2.E, O3.E, O4.E, O5.E, O6.E, O7.E) throws -> Element)
            -> Observable<Element> {
        return CombineLatest7(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(),
            debounceDependencies: debounceDependencies, resultSelector: resultSelector
        )
    }
}

extension ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType, O6: ObservableType, O7: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7, debounceDependencies: Bool = false)
            -> Observable<(O1.E, O2.E, O3.E, O4.E, O5.E, O6.E, O7.E)> {
        return CombineLatest7(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(),
            debounceDependencies: debounceDependencies,
            resultSelector: { ($0, $1, $2, $3, $4, $5, $6) }
        )
    }
}

final class CombineLatestSink7_<E1, E2, E3, E4, E5, E6, E7, Observer: ObserverType> : CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = CombineLatest7<E1, E2, E3, E4, E5, E6, E7, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil
    var _latestElement6: E6! = nil
    var _latestElement7: E7! = nil

    init(parent: Parent, observer: Observer, cancel: Cancelable) {
        self._parent = parent
        super.init(arity: 7, observer: observer, cancel: cancel)
    }

    func run(debounceDependencies: Bool) -> Disposable {
        var disposables: [Disposable] = []
        
        if debounceDependencies {
            for (index, source) in _parent.observableSources.enumerated() {
                for leafSource in source.leafSources.deduplicatedByPointer() {
                    let subscription = SingleAssignmentDisposable()
                    
                    let observer = CombineLatestEraseObserver(lock: _lock, parent: self, index: index, this: subscription)
                    subscription.setDisposable(leafSource.subscribeAny { observer.on($0) })
                    disposables.append(subscription)
                }
            }
        }

        let subscription1 = SingleAssignmentDisposable()
        let subscription2 = SingleAssignmentDisposable()
        let subscription3 = SingleAssignmentDisposable()
        let subscription4 = SingleAssignmentDisposable()
        let subscription5 = SingleAssignmentDisposable()
        let subscription6 = SingleAssignmentDisposable()
        let subscription7 = SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)
        let observer6 = CombineLatestObserver(lock: self._lock, parent: self, index: 5, setLatestValue: { (e: E6) -> Void in self._latestElement6 = e }, this: subscription6)
        let observer7 = CombineLatestObserver(lock: self._lock, parent: self, index: 6, setLatestValue: { (e: E7) -> Void in self._latestElement7 = e }, this: subscription7)

        if debounceDependencies {
            // We avoid using MainScheduler here, as we _always_ want these subscriptions to be dispatched
            // asynchronously rather than run directly.
            let mainScheduler = ConcurrentDispatchQueueScheduler(queue: DispatchQueue.main)
            subscription1.setDisposable(_parent._source1.observeOn(mainScheduler).subscribe(observer1))
            subscription2.setDisposable(_parent._source2.observeOn(mainScheduler).subscribe(observer2))
            subscription3.setDisposable(_parent._source3.observeOn(mainScheduler).subscribe(observer3))
            subscription4.setDisposable(_parent._source4.observeOn(mainScheduler).subscribe(observer4))
            subscription5.setDisposable(_parent._source5.observeOn(mainScheduler).subscribe(observer5))
            subscription6.setDisposable(_parent._source6.observeOn(mainScheduler).subscribe(observer6))
            subscription7.setDisposable(_parent._source7.observeOn(mainScheduler).subscribe(observer7))
        } else {
         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))
         subscription6.setDisposable(self._parent._source6.subscribe(observer6))
         subscription7.setDisposable(self._parent._source7.subscribe(observer7))
        }

        return Disposables.create(disposables + [
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5,
                subscription6,
                subscription7
        ])
    }

    override func getResult() throws -> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5, self._latestElement6, self._latestElement7)
    }
}

final class CombineLatest7<E1, E2, E3, E4, E5, E6, E7, Result> : Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5, E6, E7) throws -> Result

    let _source1: Observable<E1>
    let _source2: Observable<E2>
    let _source3: Observable<E3>
    let _source4: Observable<E4>
    let _source5: Observable<E5>
    let _source6: Observable<E6>
    let _source7: Observable<E7>

    let _debounceDependencies: Bool
    let _resultSelector: ResultSelector

    init(source1: Observable<E1>, source2: Observable<E2>, source3: Observable<E3>, source4: Observable<E4>, source5: Observable<E5>, source6: Observable<E6>, source7: Observable<E7>, debounceDependencies: Bool, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5
        self._source6 = source6
        self._source7 = source7

        self._debounceDependencies = debounceDependencies
        self._resultSelector = resultSelector
    }

    override func run<Observer: ObserverType>(_ observer: Observer, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where Observer.Element == Result {
        let sink = CombineLatestSink7_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run(debounceDependencies: _debounceDependencies)
        return (sink: sink, subscription: subscription)
    }
}



// 8

extension ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType, O6: ObservableType, O7: ObservableType, O8: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7, _ source8: O8, debounceDependencies: Bool = false, resultSelector: @escaping (O1.E, O2.E, O3.E, O4.E, O5.E, O6.E, O7.E, O8.E) throws -> Element)
            -> Observable<Element> {
        return CombineLatest8(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(), source8: source8.asObservable(),
            debounceDependencies: debounceDependencies, resultSelector: resultSelector
        )
    }
}

extension ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    public static func combineLatest<O1: ObservableType, O2: ObservableType, O3: ObservableType, O4: ObservableType, O5: ObservableType, O6: ObservableType, O7: ObservableType, O8: ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7, _ source8: O8, debounceDependencies: Bool = false)
            -> Observable<(O1.E, O2.E, O3.E, O4.E, O5.E, O6.E, O7.E, O8.E)> {
        return CombineLatest8(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(), source8: source8.asObservable(),
            debounceDependencies: debounceDependencies,
            resultSelector: { ($0, $1, $2, $3, $4, $5, $6, $7) }
        )
    }
}

final class CombineLatestSink8_<E1, E2, E3, E4, E5, E6, E7, E8, Observer: ObserverType> : CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = CombineLatest8<E1, E2, E3, E4, E5, E6, E7, E8, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil
    var _latestElement6: E6! = nil
    var _latestElement7: E7! = nil
    var _latestElement8: E8! = nil

    init(parent: Parent, observer: Observer, cancel: Cancelable) {
        self._parent = parent
        super.init(arity: 8, observer: observer, cancel: cancel)
    }

    func run(debounceDependencies: Bool) -> Disposable {
        var disposables: [Disposable] = []
        
        if debounceDependencies {
            for (index, source) in _parent.observableSources.enumerated() {
                for leafSource in source.leafSources.deduplicatedByPointer() {
                    let subscription = SingleAssignmentDisposable()
                    
                    let observer = CombineLatestEraseObserver(lock: _lock, parent: self, index: index, this: subscription)
                    subscription.setDisposable(leafSource.subscribeAny { observer.on($0) })
                    disposables.append(subscription)
                }
            }
        }

        let subscription1 = SingleAssignmentDisposable()
        let subscription2 = SingleAssignmentDisposable()
        let subscription3 = SingleAssignmentDisposable()
        let subscription4 = SingleAssignmentDisposable()
        let subscription5 = SingleAssignmentDisposable()
        let subscription6 = SingleAssignmentDisposable()
        let subscription7 = SingleAssignmentDisposable()
        let subscription8 = SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)
        let observer6 = CombineLatestObserver(lock: self._lock, parent: self, index: 5, setLatestValue: { (e: E6) -> Void in self._latestElement6 = e }, this: subscription6)
        let observer7 = CombineLatestObserver(lock: self._lock, parent: self, index: 6, setLatestValue: { (e: E7) -> Void in self._latestElement7 = e }, this: subscription7)
        let observer8 = CombineLatestObserver(lock: self._lock, parent: self, index: 7, setLatestValue: { (e: E8) -> Void in self._latestElement8 = e }, this: subscription8)

        if debounceDependencies {
            // We avoid using MainScheduler here, as we _always_ want these subscriptions to be dispatched
            // asynchronously rather than run directly.
            let mainScheduler = ConcurrentDispatchQueueScheduler(queue: DispatchQueue.main)
            subscription1.setDisposable(_parent._source1.observeOn(mainScheduler).subscribe(observer1))
            subscription2.setDisposable(_parent._source2.observeOn(mainScheduler).subscribe(observer2))
            subscription3.setDisposable(_parent._source3.observeOn(mainScheduler).subscribe(observer3))
            subscription4.setDisposable(_parent._source4.observeOn(mainScheduler).subscribe(observer4))
            subscription5.setDisposable(_parent._source5.observeOn(mainScheduler).subscribe(observer5))
            subscription6.setDisposable(_parent._source6.observeOn(mainScheduler).subscribe(observer6))
            subscription7.setDisposable(_parent._source7.observeOn(mainScheduler).subscribe(observer7))
            subscription8.setDisposable(_parent._source8.observeOn(mainScheduler).subscribe(observer8))
        } else {
         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))
         subscription6.setDisposable(self._parent._source6.subscribe(observer6))
         subscription7.setDisposable(self._parent._source7.subscribe(observer7))
         subscription8.setDisposable(self._parent._source8.subscribe(observer8))
        }

        return Disposables.create(disposables + [
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5,
                subscription6,
                subscription7,
                subscription8
        ])
    }

    override func getResult() throws -> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5, self._latestElement6, self._latestElement7, self._latestElement8)
    }
}

final class CombineLatest8<E1, E2, E3, E4, E5, E6, E7, E8, Result> : Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5, E6, E7, E8) throws -> Result

    let _source1: Observable<E1>
    let _source2: Observable<E2>
    let _source3: Observable<E3>
    let _source4: Observable<E4>
    let _source5: Observable<E5>
    let _source6: Observable<E6>
    let _source7: Observable<E7>
    let _source8: Observable<E8>

    let _debounceDependencies: Bool
    let _resultSelector: ResultSelector

    init(source1: Observable<E1>, source2: Observable<E2>, source3: Observable<E3>, source4: Observable<E4>, source5: Observable<E5>, source6: Observable<E6>, source7: Observable<E7>, source8: Observable<E8>, debounceDependencies: Bool, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5
        self._source6 = source6
        self._source7 = source7
        self._source8 = source8

        self._debounceDependencies = debounceDependencies
        self._resultSelector = resultSelector
    }

    override func run<Observer: ObserverType>(_ observer: Observer, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where Observer.Element == Result {
        let sink = CombineLatestSink8_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run(debounceDependencies: _debounceDependencies)
        return (sink: sink, subscription: subscription)
    }
}


